version: '3.8'

services:
  # Aplicación principal
  main_app:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - ./:/app
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:0000@db:5432/bd_actividades_historicas
    depends_on:
      - db
    restart: unless-stopped

  # Servicio Nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
    depends_on:
      - main_app
    restart: unless-stopped

  # Servicio para monitoreo
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    environment:
      - POSTGRES_DB=bd_actividades_historicas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
    ports:
      - "5432:5432"

volumes:
  grafana-storage:
  postgres_data: 