global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'phi-main-app'
    static_configs:
      - targets: ['main_app:8050']
    metrics_path: '/health'
    scrape_interval: 30s

  - job_name: 'phi-streamlit-apps'
    static_configs:
      - targets: ['main_app:8501', 'main_app:8502', 'main_app:8503']
    scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s 